[package]
name = "money-jar-core"
version = "0.1.0"
edition = "2024"

[dependencies]
diesel = { version = "2.2.10", features = ["sqlite", "returning_clauses_for_sqlite_3_35"] }
dotenvy = "0.15.7"
uuid = { version = "1.16.0", features = ["v4"] }
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"
